# .yamllint.yaml
extends: default

# define what yamllint considers yaml files
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '!.github/workflows/*.yml'  # Exclude GitHub workflow files
  - '*.md'  # Check markdown files for frontmatter

# For markdown files, only check between --- delimiters
rules:
  # Configure rules that need special handling
  document-start:
    present: true        # Require --- for markdown frontmatter
    level: error        # This helps identify frontmatter boundaries

  document-end:
    present: true       # Require ... after frontmatter
    level: error       # This helps identify frontmatter boundaries
  
  indentation:
    spaces: consistent    # Allow flexible indentation
    indent-sequences: whatever  # Allow flexible sequence indentation
    check-multi-line-strings: false
    level: warning      # Only warn about indentation issues

  # Disable rules that conflict with our patterns
  line-length: disable    # Content may have long lines
  truthy: disable        # Allow various boolean formats
  brackets: disable      # We use quotes to catch array syntax
  key-ordering: disable     # Keys can be in any order

  # Configure rules for our specific needs
  quoted-strings:
    level: warning
    quote-type: any     # Allow either quote type
    required: only-when-needed  # Only require quotes when needed
    extra-allowed:      # Properties that can be either quoted or unquoted
      - '^date_.*:'     # Timestamp properties
      - '^.*_date:'
      - '^last_.*:'
      - '^created_at:'
      - '^datetime:'
      - '^uuid:'
      - '^site_uuid:'
      - '^url:'
      - '^og_.*_url:'   # Matches og_image_url, og_video_url, etc.
      - '^og_error_message:'
      - '^error_message:'
      - '^.*_error:'
      - '^description:'  # When contains special chars
      - '^title:'       # When contains special chars
      - '^parent_org:'  # Backlinks must be quoted
      - '^product_of:'  # Backlinks must be quoted
      - '^.*_backlink:' # Any other backlink properties
    allow-quoted-quotes: true  # Allow nested quotes

  # Spacing and formatting rules
  comments:
    level: warning
    require-starting-space: true

  empty-lines:
    level: warning
    max: 2              # Allow up to 2 blank lines for markdown readability
    max-end: 1

  colons:
    level: warning
    max-spaces-before: 0
    max-spaces-after: 1

  # Basic file hygiene
  key-duplicates: disable    # Allow duplicates since we're handling AI-generated content
  new-line-at-end-of-file:  # POSIX standard, helps with text processing
    level: warning
  trailing-spaces:          # Remove unnecessary whitespace
    level: warning